# Generated by Django 2.2.1 on 2019-05-19 23:36

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadLiviana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Propiedad', max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='property_image')),
            ],
            options={
                'verbose_name': 'propiedad',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(validators=[app.models.validate_monday])),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PropiedadLiviana')),
            ],
            options={
                'unique_together': {('semana', 'propiedad')},
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='propiedadliviana',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TipoPropiedad'),
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ubication', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='property_image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('precioBase', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.Reserva')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Propiedad', max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('dpto', models.CharField(blank=True, max_length=10)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Calle')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TipoPropiedad')),
            ],
            options={
                'unique_together': {('calle', 'numero', 'piso', 'dpto')},
            },
        ),
        migrations.CreateModel(
            name='OfertaSubasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subasta')),
            ],
            options={
                'unique_together': {('cliente', 'subasta')},
            },
        ),
    ]
