# Generated by Django 2.1.9 on 2019-07-07 21:24

import app.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tarjeta_credito', models.CharField(default='000000000000000', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(default=app.models.a_year_from_now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
            ],
            options={
                'ordering': ('expiration_date',),
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('tipo', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('arancel', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaSubasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('dpto', models.CharField(blank=True, max_length=10)),
                ('image', models.TextField(blank=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('calle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Calle')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(validators=[app.models.validate_monday])),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioMembresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('pendiente', models.BooleanField(default=True)),
                ('a_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Membresia')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('semana', models.DateField()),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('fecha_fin', models.DateField(null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('ganador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subastas_ganadas', to='app.Cliente')),
                ('ofertantes', models.ManyToManyField(related_name='_subasta_ofertantes_+', through='app.OfertaSubasta', to='app.Cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='app.Propiedad')),
            ],
        ),
        migrations.AddField(
            model_name='ofertasubasta',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subasta'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='membresia',
            field=models.ForeignKey(default='ESTANDAR', on_delete=django.db.models.deletion.CASCADE, to='app.Membresia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='subastas_ofertadas',
            field=models.ManyToManyField(through='app.OfertaSubasta', to='app.Subasta'),
        ),
        migrations.AddField(
            model_name='calle',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Localidad'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('semana', 'propiedad')},
        ),
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('calle', 'numero', 'piso', 'dpto')},
        ),
    ]
