# Generated by Django 2.2.1 on 2019-06-08 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadliviana',
            name='tipo',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='property_image'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Propiedad'),
        ),
        migrations.DeleteModel(
            name='Properties',
        ),
        migrations.DeleteModel(
            name='PropiedadLiviana',
        ),
    ]
