# Generated by Django 2.2.1 on 2019-05-19 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.PropiedadLiviana'),
        ),
    ]
