# Generated by Django 2.2.1 on 2019-05-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_properties_date_posted2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='date_posted2',
        ),
    ]
