# Generated by Django 2.2.1 on 2019-06-11 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190607_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='EstadoSubasta',
        ),
    ]
