# Generated by Django 2.1.9 on 2019-07-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hotsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsale',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
