# Generated by Django 2.1.9 on 2019-07-08 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190708_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsale',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotsales_adquiridos', to='app.Cliente'),
        ),
    ]
