# Generated by Django 2.2.1 on 2019-06-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190611_0022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ofertasubasta',
            unique_together=set(),
        ),
    ]
