# Generated by Django 2.2.1 on 2019-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_properties_date_posted2'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(blank=True, upload_to='property_image'),
        ),
    ]
