# Generated by Django 2.2.1 on 2019-05-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_properties_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='image',
            new_name='img',
        ),
    ]
