# Generated by Django 2.2.1 on 2019-05-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190512_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='img',
        ),
    ]
