# Generated by Django 2.1.9 on 2019-07-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcambiomembresia',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddField(
            model_name='solicitudcambiomembresia',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
