# Generated by Django 2.2.1 on 2019-06-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_imagenpropiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.ImagenPropiedad'),
        ),
    ]
