# Generated by Django 2.2.1 on 2019-05-16 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_remove_properties_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Propiedad', max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('piso', models.CharField(blank=True, max_length=10)),
                ('dpto', models.CharField(blank=True, max_length=10)),
                ('calle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.Calle')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Propiedad')),
            ],
            options={
                'unique_together': {('semana', 'propiedad')},
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioBase', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Estado')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TipoPropiedad'),
        ),
        migrations.CreateModel(
            name='OfertaSubasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Subasta')),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Provincia')),
            ],
        ),
        migrations.AddField(
            model_name='calle',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Localidad'),
        ),
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('calle', 'numero', 'piso', 'dpto')},
        ),
    ]
