# Generated by Django 2.1.9 on 2019-07-14 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190714_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
