# Generated by Django 2.2.1 on 2019-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190616_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
