# Generated by Django 2.1.9 on 2019-07-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pago_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsale',
            options={'ordering': ['semana']},
        ),
    ]
