# Generated by Django 2.2.1 on 2019-05-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_properties_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadLiviana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva Propiedad', max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200, unique=True)),
                ('imagen', models.ImageField(default='default.jpg', upload_to='property_image')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.TipoPropiedad')),
            ],
            options={
                'verbose_name': 'propiedad',
            },
        ),
    ]
