# Generated by Django 2.1.9 on 2019-07-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190714_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subasta',
            options={'ordering': ['semana']},
        ),
        migrations.AlterUniqueTogether(
            name='hotsale',
            unique_together={('semana', 'propiedad')},
        ),
        migrations.AlterUniqueTogether(
            name='subasta',
            unique_together={('semana', 'propiedad')},
        ),
    ]
