# Generated by Django 2.2.1 on 2019-06-17 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190616_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='calle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Calle'),
        ),
    ]
