# Generated by Django 2.2.1 on 2019-06-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190616_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
