# Generated by Django 2.1.9 on 2019-07-15 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190715_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ('semana',)},
        ),
    ]
