# Generated by Django 2.2.1 on 2019-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190617_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='es_activa',
            field=models.BooleanField(default=True),
        ),
    ]
