# Generated by Django 2.2.1 on 2019-06-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190617_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='estado',
        ),
        migrations.AddField(
            model_name='subasta',
            name='es_activa',
            field=models.BooleanField(default=True),
        ),
    ]
