# Generated by Django 2.2.2 on 2019-06-18 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190617_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
