# Generated by Django 2.2.1 on 2019-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190607_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresia',
            name='arancel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membresia',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
