# Generated by Django 2.2.2 on 2019-06-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
