# Generated by Django 2.2.2 on 2019-06-16 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='tarjeta_credito',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
