# Generated by Django 2.2.2 on 2019-06-17 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190616_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tarjeta_credito',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
