# Generated by Django 2.2.1 on 2019-06-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190616_2336'),
        ('users', '0007_auto_20190617_1639'),
    ]

    operations = [
    ]
