# Generated by Django 2.2.1 on 2019-06-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20190617_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='membresia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Membresia'),
        ),
    ]
