# Generated by Django 2.2.1 on 2019-05-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='calle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='common.Calle'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='dpto',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='numero',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='piso',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='titulo',
            field=models.CharField(default='Nueva Propiedad', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='propiedad',
            unique_together={('calle', 'numero', 'piso', 'dpto')},
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='direccion',
        ),
        migrations.DeleteModel(
            name='Direccion',
        ),
    ]
